### PR TITLE
Add contact us section #25 

### LINKED ISSUE #25: Add contact us section
please assign it to me under JWOC'2024.

### PR DESCRIPTION
**Pull request by vishal2005025**
# closes #25

### CODE REVIEW

**Comment by vishal2005025** [comment]
Sir , please review and please change the label of this issue to hard as I have spent almost one day to complete the issue.
please change..

**Comment by Animesh606** [comment]
The form is showing odd for the site make it smaller from height like font size or other
Or make different page for this.
Add mobile, email and other details with secret file(.env) to make it hard issue.

**Comment by vishal2005025** [comment]
ok!

**Comment by vishal2005025** [comment]
sir , please review and merge this issue.

**Comment by vishal2005025** [comment]
sir , please merge..

**Comment by Animesh606** [comment]
Is it the final version but there is a responsive problem.
A horizontal bar coming in home page

**Pull request merged**
